services:
  db:
    image: mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ABCabc123
      MYSQL_USER:
      MYSQL_PASSWORD:
      MYSQL_DATABASE: maturita
    volumes:
      - data:/var/lib/mysql
    ports:
      - 4306:3306
    healthcheck:
      test: ["CMD", "/usr/local/bin/healthcheck.sh", "--connect"]
      interval: 5s
      timeout: 2s
      retries: 20

  web:
    build: .
    restart: unless-stopped
    ports:
      - 9999:80
    volumes:
      - uploads:/var/www/html/uploads
    depends_on:
      db:
        condition: service_healthy

volumes:
  data:
  uploads:
