<div class="container">
    <div class="sidebar">
        <h3>Novinky</h3>
        <p>Zde se objeví nové inforace o účtu.</p>
    </div>

    <div class="main-content">
        <div class="profile-header">
            <img src="pfp/muz3.png" alt="Profilová fotka" class="profile-picture">
            <div class="profile-info">
                <h1><?= htmlspecialchars($uzivatel['user_name']) ?></h1>
                <p><?= htmlspecialchars($uzivatel['bio'] ?? 'Zatím žádné informace.') ?></p>
            </div>
        </div>

        <div class="profile-stats">
            <div>
                <span>0</span>
                Sledujících
            </div>
            <div>
                <span>0</span>
                Sleduje
            </div>
        </div>

        <form class="profile-upload" method="post" enctype="multipart/form-data">
            <label for="profilovka">Změnit profilovou fotku</label>
            <input type="file" id="profilovka" name="profilovka">
            <button class="save-button" type="submit">Změnit</button>
        </form>


        <form class="profile-bio" method="post">
            <label for="bio">Editujte svůj popis:</label>
            <textarea id="bio" name="bio"
                placeholder="Napište něco o sobě..."><?= htmlspecialchars($uzivatel['bio'] ?? '') ?></textarea>
            <button class="save-button" type="submit">Uložit</button>
        </form>


        <div class="profile-nav">
            <a href="prispevky?liked=1">To se mi líbí</a>
            <br />
            <p>Příspěvky</p>

        </div>


        <div class="posts-container">
            <?php if (!empty($prispevky)): ?>
                <?php foreach ($prispevky as $prispevek): ?>
                    <div class="post-item">
                        <div>
                            <p><?= htmlspecialchars($prispevek['text']) ?></p>
                        </div>

                        <div><?php if (!empty($prispevek['picture'])): ?>
                                <img src="<?= htmlspecialchars($prispevek['picture']) ?>" width="250" alt="Příspěvek">
                            <?php endif; ?>
                        </div>

                        <div class="post-actions">
                            <button class="delete-button" onclick="deletePost(<?= $prispevek['id'] ?>)">Delete</button>
                        </div>
                    </div>
                <?php endforeach; ?>
            <?php else: ?>
                <p>Žádné příspěvky nenalezeny.</p>
            <?php endif; ?>
        </div>
    </div>
</div>