<div class="login-container">
    <form method="POST" class="login-form">
        <h2>Registrace</h2>
        <label for="username">Uživatelské jméno:</label>
        <div class="username-container">
            <input type="text" id="username" name="username" required>
        </div>

        <label for="password">Heslo:</label>
        <div class="password-container">
            <input type="password" id="password" name="password" required />
            <span id="toggle-password" onclick="togglePasswordVisibility();">
                <svg id="eye-icon" xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24"
                    fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                    <path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path>
                    <circle cx="12" cy="12" r="3"></circle>
                </svg>
            </span>
        </div>

        <label for="password-repeat">Heslo znovu:</label>
        <div class="password-container">
            <input type="password" id="password-repeat" name="password-repeat" required />
            <span id="toggle-password" onclick="togglePasswordVisibility(true);">
                <svg id="eye-icon-repeat" xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24"
                    fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                    <path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path>
                    <circle cx="12" cy="12" r="3"></circle>
                </svg>
            </span>
        </div>
        <label for="email">Email:</label>
        <input type="email" id="email" name="email" class="details" required>
        <label for="phone">Telefon:</label>
        <input type="number" id="phone" name="phone" class="details" required>
        <label for="dateOfBirth">Datum narození:</label>
        <input type="date" id="dateOfBirth" name="dateOfBirth" class="details" required>



        <button type="submit">Registrovat se</button>
        <?php if (isset($_GET['zprava']) && $_GET['zprava'] === 'chyba'): ?>
            <span class="chyba">Chyba</span>
        <?php endif; ?>
        <?php if (isset($_GET['zprava']) && $_GET['zprava'] === 'heslo'): ?>
            <span class="chyba">Hesla se neschodují</span>
        <?php endif; ?>
        <p>Máte účet? <a href="/login">Přihlašte se</a></p>
    </form>
</div>