<!DOCTYPE html>
<html lang="cs-cz">

<head>
    <base href="/localhost" />
    <meta charset="UTF-8" />
    <title><?= $titulek ?></title>
    <meta name="description" content="<?= $popis ?>" />
    <meta name="keywords" content="<?= $klicova_slova ?>" />
    <link rel="stylesheet" href="styles/globalStyles.css" type="text/css" />
    <link rel="stylesheet" href="styles/<?= $stylesheet ?>" type="text/css" />
    <?= $skripty ?>
</head>

<body>
    <img src="obrazky/uvod.png" alt="background" class="background">
    <header class="header">
        <img src="logo/logo.png" alt="logo" style="width: 160px; height: 60px;">
    </header>

    <nav class="menu">
        <div class="menu-items">
            <a href="uvod">Úvod</a>
            <a href="prispevky">Příspěvky</a>
            <a href="chat">Chat</a>
            <a href="ucet">Účet</a>
        </div>
    </nav>

    <article>
        <?php $this->kontroler->vypisPohled(); ?>
    </article>

</body>

</html>