<div class="intro-container">
    <div class="intro-header">
        <p>Spojujeme fitness nadšence a motivujeme k lepším výkonům.</p>
    </div>

    <div class="content">
        <div class="left">
            <img src="obrazky/muz1.png" alt="Fitness Inspiration 1" class="imgtl" />
            <img src="obrazky/muz2.png" alt="Fitness Inspiration 2" class="imgbl" />
        </div>
        <div class="center">
            <p>Sdílej své pokroky, tréninkové plány nebo inspiraci s ostatními uživateli. Staň se součástí fitness
                komunity, která tě podpoří na tvé cestě.</p>
            <p>Spoj se přímo s ostatními uživateli. Sdílej tipy, motivaci nebo si jen popovídej s lidmi, kteří mají
                stejné zájmy jako ty.</p>
            <p>Prohlížej si příspěvky od ostatních uživatelů, najdi nové tréninkové nápady nebo výzvy a motivuj se
                úspěchy ostatních.</p>
            <p>Připoj se k lidem z celého světa, kteří sdílejí tvůj zápal pro fitness a zdravý životní styl.</p>
        </div>
        <div class="right">
            <div class="button-container">
                <a href="prihlaseni" class="button">Přihlášení</a>
                <a href="registrace" class="button">Registrace</a>
            </div>
            <img src="obrazky/zena.png" alt="Fitness Inspiration 3" class="imgr" />
        </div>
    </div>

    <a href="pokracovat" class="continue-button">Pokračovat bez registrace</a>
</div>