<div class="hero-section">
  <div class="hero-content">
    <?= $uvod ?>
    <div class="cta-buttons">
      <a href="login" class="btn btn-primary">Příhlášení</a>
      <a href="registrace" class="btn btn-secondary">Registrace</a>
    </div>
    <div class="cta-buttons">
      <a href="prispevky" class="btn btn-secondary">Pokračovat bez registrace</a>
    </div>
  </div>

  <div class="hero-image">
    <img src="obrazky/muz2.png" alt="Fitness user" />
    <div class="chat-bubble bubble-1">
      <p>Jaké cviky doporučuješ na nohy?</p>
      <span>10:00</span>
    </div>
    <div class="chat-bubble bubble-2">
      <p>Skvělý progress, jen tak dá!</p>
      <span>10:02</span>
    </div>
  </div>
</div>