<div class="ucet-info">
    <div class="ucet-container">
        <a href="login">Přihlášení</a>
        <a href="registrace">Registrace</a>
    </div>

    <div class="nav-container">
        <nav>
            <a href="ucet/nastaveni">Nastavení</a>
            <a href="ucet/info">Info</a>
            <a href="ucet/statistiky">Statistiky</a>
            <a href="ucet/profil">Profil</a>
        </nav>
    </div>
</div>