<div class="ucet-statistiky">
    <div class="ucet-container">
        <div>
            <p>počet komentářu: <?= $this->data['comentCount'] ?></p>
            <p>počet lajků: <?= $this->data['likeCount'] ?>	</p>
        </div>
        
    </div>
    <nav>
        <a href="ucet/nastaveni">Nastavení</a>
        <a href="ucet/info">Info</a>
        <a href="ucet/statistiky">Statistiky</a>
    </nav>
</div>